### ISSUE TITLE
AvstpWrapper constructor concurrency related crash

### ISSUE THREAD

**Issue by AkarinVS** [AkarinVS/fmtconv#1]
This script, when run with `vspipe -p test.vpy .`, has a very high probability of crashing with 0xc0000005 (access violation) on Windows (with VapourSynth R53):

```python
import vapoursynth as vs
core = vs.core

src = core.std.BlankClip(width=1920, height=1080,format=vs.YUV420P8,length=1000,fpsnum=24000,fpsden=1001)
y = core.std.ShufflePlanes(src, 0, vs.GRAY).fmtc.resample(1920, 1080, sx=1.50, kernel='bicubic')
u = core.std.ShufflePlanes(src, 1, vs.GRAY).fmtc.resample(1920, 1080, sx=0.25, kernel='bicubic')
v = core.std.ShufflePlanes(src, 2, vs.GRAY).fmtc.resample(1920, 1080, sx=0.25, kernel='bicubic')

core.std.Expr([y,u,v], "x y z max max").set_output()
```

Tested with fmtconv r22 official release, and VapourSynth R53 amd64 official release.

The issue is that `AvstpWrapper` singleton is only constructed when first used by `fmtcl::FilterResize`.
https://github.com/AkarinVS/fmtconv/blob/4f187bf5b7fe116d98a55910d597146b6b3a79a8/src/fmtcl/FilterResize.cpp#L64
The vpy above is written in such a way that clip `y`, `u` and `v` are fully symmetric in the data flow graph, and as a consequence, VS has a high probability of scheduling to execute them at around the same time. These concurrent `fmtcl::FilterResize` will each race to create the `AvstpWrapper` singleton, because `AvstpFinder::find_lib` is slow, there is a large window of vulnerability where a 2nd thread will find that the `AvstpWrapper` singleton is only partially constructed (vtable initialized and all function pointers initialized to 0) and will proceed to use that, and then crash when calling
https://github.com/AkarinVS/fmtconv/blob/4f187bf5b7fe116d98a55910d597146b6b3a79a8/src/fmtcl/FilterResize.cpp#L519

Here is one example gdb stack trace for two related threads exhibiting this crash:
```
Thread 22 (Thread 828.0x7bc):
#0  0x00007ffbc52f0d2a in ntdll!ZwSetEvent () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ffbc5298c66 in ntdll!RtlpUnWaitCriticalSection () from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00007ffbc5297302 in ntdll!RtlLeaveCriticalSection () from C:\Windows\SYSTEM32\ntdll.dll
#3  0x00007ffbc53521da in ntdll!RtlpNtMakeTemporaryKey () from C:\Windows\SYSTEM32\ntdll.dll
#4  0x00007ffbc5308f3d in ntdll!memset () from C:\Windows\SYSTEM32\ntdll.dll
#5  0x00007ffbc52903c8 in ntdll!RtlFreeHeap () from C:\Windows\SYSTEM32\ntdll.dll
#6  0x00007ffbc528695c in ntdll!RtlEqualUnicodeString () from C:\Windows\SYSTEM32\ntdll.dll
#7  0x00007ffbc5287ba3 in ntdll!RtlEqualUnicodeString () from C:\Windows\SYSTEM32\ntdll.dll
#8  0x00007ffbc52a7a2d in ntdll!LdrGetDllHandleEx () from C:\Windows\SYSTEM32\ntdll.dll
#9  0x00007ffbc52a6de9 in ntdll!LdrLoadDll () from C:\Windows\SYSTEM32\ntdll.dll
#10 0x00007ffbc2538e4a in LoadLibraryExW () from C:\Windows\system32\KernelBase.dll
#11 0x00007ffbaf8e1a89 in ?? () from D:\progs\vapoursynth.R53\vapoursynth64\plugins\fmtconv.dll
#12 0x00007ffbaf8e1d03 in ?? () from D:\progs\vapoursynth.R53\vapoursynth64\plugins\fmtconv.dll
#13 0x00007ffbaf83dd3e in ?? () from D:\progs\vapoursynth.R53\vapoursynth64\plugins\fmtconv.dll
#14 0x00007ffbaf8d9cee in ?? () from D:\progs\vapoursynth.R53\vapoursynth64\plugins\fmtconv.dll
#15 0x00007ffbaf8d98c7 in ?? () from D:\progs\vapoursynth.R53\vapoursynth64\plugins\fmtconv.dll
#16 0x00007ffbaf8d930e in ?? () from D:\progs\vapoursynth.R53\vapoursynth64\plugins\fmtconv.dll
#17 0x00007ffbaf8e0e86 in ?? () from D:\progs\vapoursynth.R53\vapoursynth64\plugins\fmtconv.dll
#18 0x00007ffbaf8d8e8f in ?? () from D:\progs\vapoursynth.R53\vapoursynth64\plugins\fmtconv.dll
#19 0x00007ffbb3b27a96 in getVapourSynthAPI () from D:\progs\vapoursynth.R53\VapourSynth.dll
#20 0x00007ffbb3b39726 in getVapourSynthAPI () from D:\progs\vapoursynth.R53\VapourSynth.dll
#21 0x00007ffbb3b3b2f3 in getVapourSynthAPI () from D:\progs\vapoursynth.R53\VapourSynth.dll
#22 0x00007ffbb50a173d in ucrtbase!_crt_atexit () from C:\Windows\SYSTEM32\ucrtbase.dll
#23 0x00007ffbc45213d2 in KERNEL32!BaseThreadInitThunk () from C:\Windows\system32\kernel32.dll
#24 0x00007ffbc52d03c4 in ntdll!RtlUserThreadStart () from C:\Windows\SYSTEM32\ntdll.dll
#25 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 31 (Thread 828.0x5c0):
#0  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

I think the code is implemented correctly, it's either a buggy compiler or, more likely, buggy compiler configuration: analysis of the assembly code of the official x64 r22 release showed that VC opts to construct the singleton on first use inside class `fmtcl::FilterResize` constructor, however, unlike g++, which will use atomic [guard variable](https://itanium-cxx-abi.github.io/cxx-abi/abi.html#once-ctor) to prevent this kind of races, VC does not use thread-safe protection at all (despite being built with multithreaded runtime `/MT`), for example, here is relevant disassembly for `fmtcl::FilterResize::FilterResize`:
```asm
18000DD1C       lea     rax, ??_7FilterResize@fmtcl@@6B@ ; const fmtcl::FilterResize::`vftable'
18000DD23       mov     [rcx], rax
18000DD26       mov     eax, cs:dword_180120EF8
18000DD2C       test    al, 1
18000DD2E       jnz     short loc_18000DD4B
18000DD30       or      eax, 1
18000DD33       mov     cs:dword_180120EF8, eax
18000DD39 loc_18000DD39:
18000DD39       call    AvstpWrapper::AvstpWrapper ; 1800B1CC0
18000DD3E       lea     rcx, AvstpWrapper::~AvstpWrapper ; 1800E9120
18000DD45       call    atexit
18000DD4A       nop
18000DD4B loc_18000DD4B:
18000DD4B       lea     rax, AvstpWrapper_singleton ; 180120F00
18000DD52       mov     [rsi+8], rax
```

**Comment by EleonoreMizo** [comment]
I just stumbled on this issue. I think it is caused by the old toolset I used to compile r22 (v120, from VS2013). Slightly later, I upgraded the toolset to v141 and recently to v142 (VS2019). The assembly code now shows a thread-safe initialization of the `AvstpWrapper` singleton with the original code—as expected, and I couldn’t reproduce any crash with the upcoming fmtconv r23.

**Comment by AkarinVS** [comment]
Yes, VS 2015 or above should generate correct thread safe initialization
code.

**Comment by AkarinVS** [comment]
fixed long time ago.
